language: objective-c
osx_image: xcode10
xcode_scheme:
- LetsMove
- LetsMove Test
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
before_deploy:
  - carthage build --no-skip-current
  - carthage archive LetsMove

